### ISSUE TITLE
update: update the code to match new features

### ISSUE THREAD

**Issue by akebu6** [hussien89aa/KotlinUdemy#20]
Update the code for all the projects in order to make them compatible with the new version on Android Studio and Kotlin 1.6.20. This is because the code the way it is will cause the app to crash or not do anything at all. This was something I struggled with when following a tutorial that was dated before the new releases.

**Note**
Also, if you cannot do it yourself, then find a maintainer to maintain this repo and keep it up-to-date for new students to easily follow and use the newly accepted features without having to search the web for the solution to why their code isn't running in the first place.

**Comment by Fr4nc1e** [comment]
Same issue here,  first, thank Dr.Hussien for the wonderful teaching, however, we really need new feature codes. I have spent a day fixing bugs, but my codes are identical to the original codes.
